### ISSUE TITLE
Why not just use fstrim in cron?

### ISSUE THREAD

**Issue by owenthewizard** [chmatse/SSDcronTRIM#10]
Like the title says, what advantages does this have over a simple `fstrim -a` in `cron.weekly` or `cron.monthly`? Is the disk usage <--> trim frequency correlation really that important that a weekly or monthly frequency does not suffice?

**Comment by cryptk** [comment]
One advantage is that this script is capable of doing some basic "sanity" tests (is the disk actually an SSD? do we have the fstrim tool?

More advanced people who understand how to schedule cron jobs themselves likely would not need this... I think this is more for people who don't really know how to do their own system maintenance, and they want a tool that they can just run and have it take care of it for them.
