### ISSUE TITLE
cron job file name indicates an unsuccesful run

### ISSUE THREAD

**Issue by toralf** [chmatse/SSDcronTRIM#3]
t44 ~ # ls -l /etc/cron.*/SSDcronTRIM*
-rwxr----- 1 root root 18414 Feb 23 19:36 /etc/cron.monthly/SSDcronTRIM_part-_slash_

Thjis is a stable Gentoo linux:
t44 ~ # fdisk -l /dev/sda

Disk /dev/sda: 223.6 GiB, 240057409536 bytes, 468862128 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 57608924-3129-49BA-8255-3EDD4D4973B9

Device           Start          End   Size Type
/dev/sda1         2048         6143     2M BIOS boot partition
/dev/sda2         6144     33560575    16G Linux swap
/dev/sda3     33560576    468862094 207.6G Linux filesystem

cfdisk :+1: 
Partition Table for /dev/sda

         ---Starting----      ----Ending-----    Start     Number of
 # Flags Head Sect  Cyl   ID  Head Sect  Cyl     Sector    Sectors
-- ----- ---- ---- ----- ---- ---- ---- ----- ----------- -----------
 1  0x00    0    2     0 0xEE   80   63 29185           1   468862127
 2  0x00    0    0     0 0x00    0    0     0           0           0
 3  0x00    0    0     0 0x00    0    0     0           0           0
 4  0x00    0    0     0 0x00    0    0     0           0           0

t44 ~ # parted -l
Model: ATA INTEL SSDSC2BF24 (scsi)
Disk /dev/sda: 240GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size    File system     Name  Flags
 1      1049kB  3146kB  2097kB                        bios_grub
 2      3146kB  17.2GB  17.2GB  linux-swap(v1)
 3      17.2GB  240GB   223GB   btrfs

**Comment by chmatse** [comment]
Hello toralf
I do not see any problems **/etc/cron.monthly/SSDcronTRIM_part-\_slash\_** is the correct filename, as long as the root partition is on a ssd (which looks okay to me, given by your infos above) and as long as the disk usage is below 30%.
